//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialNetwork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public Post()
        {
            this.Comments = new HashSet<Comment>();
            this.UsersLiked = new HashSet<AspNetUser>();
        }
    
        public int PostId { get; set; }
        public string Text { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int Votes { get; set; }
        public string AuthorId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<AspNetUser> UsersLiked { get; set; }
    }
}
